### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#153]
Got this issue when deploying the backend.

```
ubuntu@ip-172-31-46-28:~/thenewboston-Backend$ git checkout origin/master
Previous HEAD position was 009d3d3 126 - university app with course and lectures read-only APIs (#144)
HEAD is now at 5ece808 fix: lectures ordered by position + type fixed (#150)
ubuntu@ip-172-31-46-28:~/thenewboston-Backend$ make deploy
# We are not building with Docker compose on purpose, so we can have just one image (and probably save disk space)
docker build . -t thenewboston-backend:current --no-cache
[+] Building 19.0s (7/17)                                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                                       0.1s
 => => transferring dockerfile: 767B                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/python:3.10.4-buster                                                                                    0.7s
 => [internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                            0.0s
 => [ 1/13] FROM docker.io/library/python:3.10.4-buster@sha256:45a640b98a6c7b83b9c4d8f7557d88f0e54783024a9d13bb1eade83724d1b3c2                            0.0s
 => [internal] load build context                                                                                                                          0.4s
 => => transferring context: 29.14kB                                                                                                                       0.4s
 => CACHED [ 2/13] WORKDIR /opt/project                                                                                                                    0.0s
 => ERROR [ 3/13] RUN set -xe     && apt-get update     && apt-get install -y --no-install-recommends build-essential     && pip install virtualenvwrapp  17.7s
------
 > [ 3/13] RUN set -xe     && apt-get update     && apt-get install -y --no-install-recommends build-essential     && pip install virtualenvwrapper poetry==1.4.2     && apt-get clean     && rm -rf /var/lib/apt/lists/*:
1.431 + apt-get update
1.715 Get:1 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
1.729 Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
1.740 Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
1.923 Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [596 kB]
2.173 Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
2.528 Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
3.737 Fetched 8727 kB in 2s (4302 kB/s)
3.737 Reading package lists...
4.578 + apt-get install -y --no-install-recommends build-essential
4.608 Reading package lists...
5.483 Building dependency tree...
5.631 Reading state information...
5.782 The following NEW packages will be installed:
5.784   build-essential
5.817 0 upgraded, 1 newly installed, 0 to remove and 146 not upgraded.
5.817 Need to get 7576 B of archives.
5.817 After this operation, 20.5 kB of additional disk space will be used.
5.817 Get:1 http://deb.debian.org/debian buster/main amd64 build-essential amd64 12.6 [7576 B]
6.146 debconf: delaying package configuration, since apt-utils is not installed
6.190 Fetched 7576 B in 0s (354 kB/s)
6.241 Selecting previously unselected package build-essential.
(Reading database ... 24614 files and directories currently installed.)
6.525 Preparing to unpack .../build-essential_12.6_amd64.deb ...
6.534 Unpacking build-essential (12.6) ...
6.618 Setting up build-essential (12.6) ...
6.666 + pip install virtualenvwrapper poetry==1.4.2
9.354 Collecting virtualenvwrapper
9.404   Downloading virtualenvwrapper-6.1.0-py3-none-any.whl (22 kB)
9.592 Collecting poetry==1.4.2
9.610   Downloading poetry-1.4.2-py3-none-any.whl (222 kB)
9.639      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.7/222.7 KB 8.9 MB/s eta 0:00:00
9.718 Collecting cachecontrol[filecache]<0.13.0,>=0.12.9
9.730   Downloading CacheControl-0.12.14-py2.py3-none-any.whl (21 kB)
9.785 Collecting shellingham<2.0,>=1.5
9.797   Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
9.843 Collecting tomli<3.0.0,>=2.0.1
9.855   Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
10.17 Collecting dulwich<0.22.0,>=0.21.2
10.19   Downloading dulwich-0.21.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (514 kB)
10.21      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 514.7/514.7 KB 34.9 MB/s eta 0:00:00
10.28 Collecting poetry-core==1.5.2
10.30   Downloading poetry_core-1.5.2-py3-none-any.whl (465 kB)
10.32      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.2/465.2 KB 33.8 MB/s eta 0:00:00
10.40 Collecting requests<3.0,>=2.18
10.42   Downloading requests-2.31.0-py3-none-any.whl (62 kB)
10.43      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 KB 7.9 MB/s eta 0:00:00
10.48 Collecting packaging>=20.4
10.49   Downloading packaging-24.0-py3-none-any.whl (53 kB)
10.50      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 KB 9.8 MB/s eta 0:00:00
10.53 Collecting lockfile<0.13.0,>=0.12.2
10.54   Downloading lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
10.75 Collecting virtualenv!=20.4.5,!=20.4.6,<21.0.0,>=20.4.3
10.77   Downloading virtualenv-20.25.3-py3-none-any.whl (3.9 MB)
10.85      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 48.8 MB/s eta 0:00:00
10.90 Collecting pexpect<5.0.0,>=4.7.0
10.91   Downloading pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
10.92      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 KB 10.8 MB/s eta 0:00:00
10.96 Collecting requests-toolbelt<0.11.0,>=0.9.1
10.97   Downloading requests_toolbelt-0.10.1-py2.py3-none-any.whl (54 kB)
10.98      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 KB 10.1 MB/s eta 0:00:00
11.07 Collecting urllib3<2.0.0,>=1.26.0
11.08   Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
11.09      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 KB 23.5 MB/s eta 0:00:00
11.12 Collecting html5lib<2.0,>=1.0
11.13   Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
11.14      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 19.0 MB/s eta 0:00:00
11.20 Collecting platformdirs<3.0.0,>=2.5.2
11.21   Downloading platformdirs-2.6.2-py3-none-any.whl (14 kB)
11.32 Collecting keyring<24.0.0,>=23.9.0
11.33   Downloading keyring-23.13.1-py3-none-any.whl (37 kB)
11.39 Collecting cleo<3.0.0,>=2.0.0
11.40   Downloading cleo-2.1.0-py3-none-any.whl (78 kB)
11.41      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 KB 14.0 MB/s eta 0:00:00
11.44 Collecting crashtest<0.5.0,>=0.4.1
11.45   Downloading crashtest-0.4.1-py3-none-any.whl (7.6 kB)
11.52 Collecting build<0.11.0,>=0.10.0
11.53   Downloading build-0.10.0-py3-none-any.whl (17 kB)
11.59 Collecting filelock<4.0.0,>=3.8.0
11.61   Downloading filelock-3.13.4-py3-none-any.whl (11 kB)
11.70 Collecting trove-classifiers>=2022.5.19
11.71   Downloading trove_classifiers-2024.4.10-py3-none-any.whl (13 kB)
11.82 Collecting poetry-plugin-export<2.0.0,>=1.3.0
11.83   Downloading poetry_plugin_export-1.7.1-py3-none-any.whl (10 kB)
11.92 Collecting jsonschema<5.0.0,>=4.10.0
11.93   Downloading jsonschema-4.21.1-py3-none-any.whl (85 kB)
11.94      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 KB 13.6 MB/s eta 0:00:00
11.99 Collecting pkginfo<2.0.0,>=1.9.4
12.00   Downloading pkginfo-1.10.0-py3-none-any.whl (30 kB)
12.04 Collecting installer<0.8.0,>=0.7.0
12.06   Downloading installer-0.7.0-py3-none-any.whl (453 kB)
12.07      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 453.8/453.8 KB 44.2 MB/s eta 0:00:00
12.15 Collecting tomlkit!=0.11.2,!=0.11.3,<1.0.0,>=0.11.1
12.16   Downloading tomlkit-0.12.4-py3-none-any.whl (37 kB)
12.20 Collecting pyproject-hooks<2.0.0,>=1.0.0
12.21   Downloading pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)
12.29 Collecting stevedore
12.30   Downloading stevedore-5.2.0-py3-none-any.whl (49 kB)
12.31      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 KB 8.5 MB/s eta 0:00:00
12.35 Collecting virtualenv-clone
12.36   Downloading virtualenv_clone-0.5.7-py3-none-any.whl (6.6 kB)
12.57 Collecting msgpack>=0.5.2
12.59   Downloading msgpack-1.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (385 kB)
12.60      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.1/385.1 KB 44.0 MB/s eta 0:00:00
14.20 Collecting rapidfuzz<4.0.0,>=3.0.0
14.23   Downloading rapidfuzz-3.8.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
14.29      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 62.6 MB/s eta 0:00:00
14.40 Collecting six>=1.9
14.42   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
14.45 Collecting webencodings
14.46   Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
14.54 Collecting attrs>=22.2.0
14.55   Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
14.56      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 KB 10.0 MB/s eta 0:00:00
15.15 Collecting rpds-py>=0.7.1
15.16   Downloading rpds_py-0.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
15.19      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 52.0 MB/s eta 0:00:00
15.28 Collecting referencing>=0.28.4
15.29   Downloading referencing-0.34.0-py3-none-any.whl (26 kB)
15.33 Collecting jsonschema-specifications>=2023.03.6
15.35   Downloading jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
15.46 Collecting jaraco.classes
15.48   Downloading jaraco.classes-3.4.0-py3-none-any.whl (6.8 kB)
15.52 Collecting jeepney>=0.4.2
15.53   Downloading jeepney-0.8.0-py3-none-any.whl (48 kB)
15.54      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 KB 6.3 MB/s eta 0:00:00
15.57 Collecting SecretStorage>=3.2
15.59   Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)
15.71 Collecting importlib-metadata>=4.11.4
15.72   Downloading importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
15.76 Collecting ptyprocess>=0.5
15.78   Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
15.82 Collecting poetry-plugin-export<2.0.0,>=1.3.0
15.83   Downloading poetry_plugin_export-1.7.0-py3-none-any.whl (10 kB)
15.86   Downloading poetry_plugin_export-1.6.0-py3-none-any.whl (10 kB)
15.88   Downloading poetry_plugin_export-1.5.0-py3-none-any.whl (10 kB)
15.93   Downloading poetry_plugin_export-1.4.0-py3-none-any.whl (10 kB)
15.96   Downloading poetry_plugin_export-1.3.1-py3-none-any.whl (10 kB)
16.04 Collecting idna<4,>=2.5
16.05   Downloading idna-3.7-py3-none-any.whl (66 kB)
16.06      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 KB 12.3 MB/s eta 0:00:00
16.11 Collecting certifi>=2017.4.17
16.13   Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
16.13      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 KB 27.9 MB/s eta 0:00:00
16.33 Collecting charset-normalizer<4,>=2
16.34   Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
16.35      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.1/142.1 KB 23.6 MB/s eta 0:00:00
16.50 Collecting distlib<1,>=0.3.7
16.52   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
16.53      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 49.1 MB/s eta 0:00:00
16.55 Collecting virtualenv!=20.4.5,!=20.4.6,<21.0.0,>=20.4.3
16.57   Downloading virtualenv-20.25.2-py3-none-any.whl (3.9 MB)
16.65      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 47.5 MB/s eta 0:00:00
16.72   Downloading virtualenv-20.25.1-py3-none-any.whl (3.8 MB)
16.79      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 61.6 MB/s eta 0:00:00
16.85   Downloading virtualenv-20.25.0-py3-none-any.whl (3.8 MB)
16.93      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 47.9 MB/s eta 0:00:00
17.00   Downloading virtualenv-20.24.7-py3-none-any.whl (3.8 MB)
17.07      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 63.3 MB/s eta 0:00:00
17.13   Downloading virtualenv-20.24.6-py3-none-any.whl (3.8 MB)
17.20      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 54.0 MB/s eta 0:00:00
17.29   Downloading virtualenv-20.24.5-py3-none-any.whl (3.7 MB)
17.31      ━━━━━━━━━━━━━━━━━━━━                     1.9/3.7 MB 109.3 MB/s eta 0:00:01
17.33 ERROR: Exception:
17.33 Traceback (most recent call last):
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
17.33     yield
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
17.33     data = self._fp.read(amt) if not fp_closed else b""
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 94, in read
17.33     self.__buf.write(data)
17.33   File "/usr/local/lib/python3.10/tempfile.py", line 483, in func_wrapper
17.33     return func(*args, **kwargs)
17.33 OSError: [Errno 28] No space left on device
17.33
17.33 During handling of the above exception, another exception occurred:
17.33
17.33 Traceback (most recent call last):
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
17.33     status = run_func(*args)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
17.33     return func(self, options, args)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
17.33     requirement_set = resolver.resolve(
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
17.33     result = self._result = resolver.resolve(
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
17.33     state = resolution.resolve(requirements, max_rounds=max_rounds)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
17.33     failure_causes = self._attempt_to_pin_criterion(name)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 211, in _attempt_to_pin_criterion
17.33     for candidate in criterion.candidates:
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
17.33     return (c for c in iterator if id(c) not in self._incompatible_ids)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
17.33     candidate = func()
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
17.33     self._link_candidate_cache[link] = LinkCandidate(
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
17.33     super().__init__(
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
17.33     self.dist = self._prepare()
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
17.33     dist = self._prepare_distribution()
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
17.33     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
17.33     return self._prepare_linked_requirement(req, parallel_builds)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 532, in _prepare_linked_requirement
17.33     local_file = unpack_url(
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 214, in unpack_url
17.33     file = get_http_url(
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 94, in get_http_url
17.33     from_path, content_type = download(link, temp_dir.path)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/download.py", line 146, in __call__
17.33     for chunk in chunks:
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 304, in _rich_progress_bar
17.33     for chunk in iterable:
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
17.33     for chunk in response.raw.stream(
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
17.33     data = self.read(amt=amt, decode_content=decode_content)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 512, in read
17.33     with self._error_catcher():
17.33   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
17.33     self.gen.throw(typ, value, traceback)
17.33   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 455, in _error_catcher
17.33     raise ProtocolError("Connection broken: %r" % e, e)
17.33 pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: OSError(28, 'No space left on device')", OSError(28, 'No space left on device'))
------
Dockerfile:12
--------------------
  11 |
  12 | >>> RUN set -xe \
  13 | >>>     && apt-get update \
  14 | >>>     && apt-get install -y --no-install-recommends build-essential \
  15 | >>>     && pip install virtualenvwrapper poetry==1.4.2 \
  16 | >>>     && apt-get clean \
  17 | >>>     && rm -rf /var/lib/apt/lists/*
  18 |
--------------------
ERROR: failed to solve: process "/bin/sh -c set -xe     && apt-get update     && apt-get install -y --no-install-recommends build-essential     && pip install virtualenvwrapper poetry==1.4.2     && apt-get clean     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 2
make: *** [Makefile:4: build] Error 1
```

**Comment by dmugtasimov** [comment]
@buckyroberts I am migrating to large EC2 instance to solve this. Working on it right now

**Comment by dmugtasimov** [comment]
Implemented here:
- https://github.com/thenewboston-developers/thenewboston-Backend/pull/156
- https://github.com/thenewboston-developers/thenewboston-Backend/pull/157
- https://github.com/thenewboston-developers/thenewboston-Backend/pull/158


The server is migrated to


@buckyroberts You might need to update your fingerprints, since the IP address has remained the same:
```
dmugtasimov@dmugtasimov-Latitude-E5550:~$ ssh ubuntu@thenewboston.network
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:0IJzVGVSp3cSOdVzSlWKDB4aUHwh/R07uxnwqtU4M5Q.
Please contact your system administrator.
Add correct host key in /home/dmugtasimov/.ssh/known_hosts to get rid of this message.
Offending ED25519 key in /home/dmugtasimov/.ssh/known_hosts:68
  remove with:
  ssh-keygen -f "/home/dmugtasimov/.ssh/known_hosts" -R "thenewboston.network"
Host key for thenewboston.network has changed and you have requested strict checking.
Host key verification failed.
dmugtasimov@dmugtasimov-Latitude-E5550:~$ ssh-keygen -f "/home/dmugtasimov/.ssh/known_hosts" -R "thenewboston.network"
# Host thenewboston.network found: line 68
/home/dmugtasimov/.ssh/known_hosts updated.
Original contents retained as /home/dmugtasimov/.ssh/known_hosts.old
dmugtasimov@dmugtasimov-Latitude-E5550:~$ ssh ubuntu@thenewboston.network
The authenticity of host 'thenewboston.network (54.187.228.170)' can't be established.
ED25519 key fingerprint is SHA256:0IJzVGVSp3cSOdVzSlWKDB4aUHwh/R07uxnwqtU4M5Q.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:64: [hashed name]
    ~/.ssh/known_hosts:68: [hashed name]
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'thenewboston.network' (ED25519) to the list of known hosts.
```
